# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: bash
        run: |
          T=`cat ./0/a.md` && D=`date` > ./0/b.md
          git config user.name  "actions-user"
          git config user.email "action@github.com"
          git add -all
          git commit -m "generated"
          git push

